### PR TITLE
Youtube video and images clone

### PR DESCRIPTION
**Pull request by frankopkusianwar**
#### What does this PR do?
- Shows the youtube clone

#### Description of Task to be completed?
- Added the menu bar.
- Added the side-bar.
- Added the video section.
- Ran validations on our Html and CSS.

#### How should this be manually tested?
- Clone this branch.
- open the index.html file on your browser

#### Screenshot
screenshot

### CODE REVIEW

**Comment by majovanilla** [comment]
# Code Review  in progress 👀 by Maria Reyes

**Comment by majovanilla** [comment]
Hey @frankopkusianwar and @okikiola11 , 👋

## You did an *amazing*🌟 ✨ job on this project! 👊🏻  💯
Your Pull Request Message and your Readme Files are excellent, too!

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Check your HTML on the validator and address the errors and warnings.
Screenshot from 2020-02-21 03-38-40

- Work on the width of your embedded video, so that it takes all the space available and looks like the original.
YOURS:
Screenshot from 2020-02-21 03-42-55
ORIGINAL:
Screenshot from 2020-02-21 03-45-06

- You can use Flexbox to center vertically the contents of your navbar to make them look better.

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- You can use http://raw.githack.com/ to create live versions of your website by pasting the HTML file link. That way you can have it available even if you haven't merged into master.


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes



You can find me on Social Media below 👇 . Remember to say hi!

[GitHub](https://github.com/majovanilla) [Twitter](https://twitter.com/MajoVanilla) [LinkedIn](https://www.linkedin.com/in/majoreyesparroquin/)

**Comment by SofiBretz** [comment]
### Changes required ♻️
### Hello team 🌟

Great work on this project, but we need to fix the issues below before moving on ⬇️

- [ ] Consider the width of your embedded video, it is an empty space on the embedded video. Please fix the width so it can look like the original page.



[OPTIONAL]

- [ ] Your Demo Link is not working, please add your demo link on the readme file.

_**After making the required changes please submit a new code review request**_
Good luck! 🍀 You are almost there! 💪

SofiBretz.

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved 🏆 

Hi @okikiola11 and @frankopkusianwar, **Congratulations** on a great work done. 👍  You did all the recommended changes. Bravo 🎈 . Your project looks great and has met all the minimum requirements. You can go ahead and merge to master and submit project completion form. 😄 
[OPTIONAL]
In the README file, replace the social media handles with your names and make the live version link work. Thanks 😄 
Good luck with your next projects ✋ 
Happy coding 💻 
Daniel Larbi Addo

**Pull request merged**
